

---
kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector: # labels are used as selectors
    app: frontend
    tier: web
    project: expense
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }} # service port
    targetPort: {{ .Values.service.targetPort }}

