kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    app: backend
    tier: backend
    project: expense
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}